//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuloCongresso.Domain.Validations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModuloCongresso.Domain.Validations.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório o preenchimento da Pergunta &quot;Dispositivo Anti-Furto Comum?&quot;.
        /// </summary>
        internal static string AntiFurtoNaoSelecionado {
            get {
                return ResourceManager.GetString("AntiFurtoNaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente não tem maioridade para cadastro..
        /// </summary>
        internal static string ClienteMaioridadeInvalido {
            get {
                return ResourceManager.GetString("ClienteMaioridadeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente informou um CPF inválido..
        /// </summary>
        internal static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado! Esqueceu sua senha?.
        /// </summary>
        internal static string CpfJaCadastrado {
            get {
                return ResourceManager.GetString("CpfJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial não pode ser menor que a data da Cotação..
        /// </summary>
        internal static string DataInicialInvalida {
            get {
                return ResourceManager.GetString("DataInicialInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente informou um e-mail inválido..
        /// </summary>
        internal static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já cadastrado! Esqueceu sua senha?.
        /// </summary>
        internal static string EmailJaCadastrado {
            get {
                return ResourceManager.GetString("EmailJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório o preenchimento da Pergunta &quot;No Colégio / Faculdade?&quot;.
        /// </summary>
        internal static string GaragemFaculdadeNaoSelecionado {
            get {
                return ResourceManager.GetString("GaragemFaculdadeNaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório o preenchimento da Pergunta &quot;Na Residência?&quot;.
        /// </summary>
        internal static string GaragemResidenciaNaoSelecionado {
            get {
                return ResourceManager.GetString("GaragemResidenciaNaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório o preenchimento da Pergunta &quot;No Trabalho?&quot;.
        /// </summary>
        internal static string GaragemTrabalhoNaoSelecionado {
            get {
                return ResourceManager.GetString("GaragemTrabalhoNaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotação não possui Modelo selecionado!.
        /// </summary>
        internal static string ModeloNaoSelecionado {
            get {
                return ResourceManager.GetString("ModeloNaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório o preenchimento da Pergunta &quot;Propriedade do Rastreador?&quot;.
        /// </summary>
        internal static string PropriedadeNaoSelecionado {
            get {
                return ResourceManager.GetString("PropriedadeNaoSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório o preenchimento da Pergunta &quot;Rastreadores/Localizadores?&quot;.
        /// </summary>
        internal static string RastreadorNaoSelecionado {
            get {
                return ResourceManager.GetString("RastreadorNaoSelecionado", resourceCulture);
            }
        }
    }
}
